language:
  - php
  - node_js

php:
  - 5.5

install:
  - composer require --dev phpunit/phpunit
  - npm install -g grunt-cli
  - npm install

script:
  - phpunit tests/ProfileFunctionsTest.php
  - grunt qunit

notifications:
  slack:
    rooms:
      - tnawebteam:C2GnodnLsxhwwGvr0xAcajzc#code-builds