language:
  - node_js
  - php

php:
  - 7.1

node_js:
  - "stable"

cache:
  directories:
  - node_modules

install:
  - composer require --dev phpunit/phpunit
  - npm install -g grunt-cli
  - npm install

script:
  - phpunit tests/ProfilePageFunctionsTest.php
  - grunt qunit

notifications:
  slack:
    rooms:
      - tna-digital:C2GnodnLsxhwwGvr0xAcajzc#code-builds