language:
  - php
  - node_js

php:
  - "7.1"

node_js:
  - "stable"

before_install:
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install stable
  - node --version

install:
  - composer require --dev phpunit/phpunit
  - npm install

script:
  - phpunit tests/ProfilePageFunctionsTest.php
  - grunt qunit

notifications:
  slack:
    rooms:
      - tnawebteam:C2GnodnLsxhwwGvr0xAcajzc#code-builds